version: "3.9"
services:
  db:
    image: postgres:15
    container_name: mindra-postgres
    restart: always
    environment:
      POSTGRES_USER: mindra
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: mindra
    ports:
      - "5432:5432"
